import { Toaster } from "@/components/ui/toaster";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["devanagari"], weight: "500" });

export const metadata: Metadata = {
	manifest: "/manifest.json",
	title: "The PUC Project",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode; 
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<main>{children}</main>
				<Toaster />
			</body>
		</html>
	);
}
